# ================================ AIRFLOW ================================
x-airflow-common:
  &airflow-common
  build: ./airflow/.
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/data:/opt/airflow/data
    - ./airflow/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  env_file:
    - ./airflow/.env
  depends_on:
    &airflow-common-depends-on
    airflow-postgres:
      condition: service_healthy

services:
  airflow-postgres:
    image: quay.io/debezium/example-postgres:2.6
    container_name: airflow-postgres
    env_file:
      - ./airflow/.env
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    depends_on:
      - statsd-exporter
    profiles:
      - airflow

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      <<: *airflow-common-depends-on
    profiles:
      - airflow

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    depends_on:
      <<: *airflow-common-depends-on
    profiles:
      - airflow

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command: version
    profiles:
      - airflow

  statsd-exporter:
    image: prom/statsd-exporter:latest
    container_name: airflow-statsd-exporter
    command: "--statsd.listen-udp=:8125 --web.listen-address=:9102"
    ports:
      - 9123:9102
      - 8125:8125/udp
    profiles:
      - airflow

# ================================ GRAFANA ================================
  prometheus:
    image: prom/prometheus:latest
    container_name: grafana-prometheus
    user: "0"
    ports:
      - 9090:9090
    volumes:
      - ./grafana/prometheus.yaml:/prometheus.yaml
    command: "--config.file=/prometheus.yaml"
    profiles:
      - grafana

  grafana:
    image: grafana/grafana:10.2.4-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/config/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - ./grafana/config/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./grafana/config/grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/config/grafana/plugins/:/var/lib/grafana/plugins/
    profiles:
      - grafana

# ================================ DB ================================
  mysql:
    image: quay.io/debezium/example-mysql:2.6
    container_name: mysql
    env_file:
      - ./db/.env
    ports:
      - 3303:3306
    profiles:
      - mysql
      - db

  postgres:
    image: quay.io/debezium/example-postgres:2.6
    container_name: postgres
    env_file:
      - ./db/.env
    ports:
      - 5434:5432
    profiles:
      - postgres
      - db

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: hive-namenode
    environment:
      CLUSTER_NAME: hive
    env_file:
      - ./db/.env
    ports:
      - 50070:50070
    profiles:
      - hive

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: hive-datanode
    env_file:
      - ./db/.env
    environment:
      SERVICE_PRECONDITION: namenode:50070
    depends_on:
      - namenode
    ports:
      - 50075:50075
    profiles:
      - hive

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    env_file:
      - ./db/.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: jdbc:postgresql://hive-metastore/metastore
      SERVICE_PRECONDITION: hive-metastore:9083
    depends_on:
      - hive-metastore
    ports:
      - 10000:10000
    profiles:
      - hive

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./db/.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    depends_on:
      - hive-metastore-postgresql
    ports:
      - 9083:9083
    profiles:
      - hive

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    depends_on:
      - datanode
    profiles:
      - hive

# ================================ SPARK ================================
  spark-master:
    build: ./spark/.
    container_name: spark-master
    hostname: spark
    env_file:
      - ./spark/.env
    environment:
      SPARK_MODE: master
    ports:
      - 10010:8080
      - 7077:7077
      - 4040-4050:4040-4050
    working_dir: /spark
    volumes:
      - ./spark/:/spark
      - ./airflow/data/:/opt/airflow/data
    profiles:
      - spark

  spark-worker-1:
    build: ./spark/.
    container_name: spark-worker-1
    ports:
      - 10011:8081
    env_file:
      - ./spark/.env
    environment:
      SPARK_MODE: worker
    working_dir: /spark
    volumes:
      - ./spark/:/spark
      - ./airflow/data/:/opt/airflow/data
    profiles:
      - spark

  spark-worker-2:
    build: ./spark/.
    container_name: spark-worker-2
    ports:
      - 10012:8081
    env_file:
      - ./spark/.env
    environment:
      SPARK_MODE: worker
    working_dir: /spark
    volumes:
      - ./spark/:/spark
      - ./airflow/data/:/opt/airflow/data
    profiles:
      - spark

# ======================= KAFKA =======================
  zookeeper:
    image: bitnamilegacy/zookeeper:3.7.0
    hostname: zookeeper
    container_name: zookeeper
    env_file:
      - ./kafka/.env
    ports:
      - "2181:2181"
    profiles:
      - kafka

  kafka1:
    image: bitnamilegacy/kafka:2.8.1
    hostname: kafka1
    container_name: kafka1
    env_file:
      - ./kafka/.env
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092,DOCKER://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka1:19092,EXTERNAL://127.0.0.1:9092,DOCKER://host.docker.internal:29092
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    profiles:
      - kafka

  kafka2:
    image: bitnamilegacy/kafka:2.8.1
    hostname: kafka2
    container_name: kafka2
    env_file:
      - ./kafka/.env
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19093,EXTERNAL://0.0.0.0:9093,DOCKER://0.0.0.0:29093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka2:19093,EXTERNAL://127.0.0.1:9093,DOCKER://host.docker.internal:29093
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "29093:29093"
    profiles:
      - kafka

  kafka3:
    image: bitnamilegacy/kafka:2.8.1
    hostname: kafka3
    container_name: kafka3
    env_file:
      - ./kafka/.env
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19094,EXTERNAL://0.0.0.0:9094,DOCKER://0.0.0.0:29094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka3:19094,EXTERNAL://127.0.0.1:9094,DOCKER://host.docker.internal:29094
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
      - "29094:29094"
    profiles:
      - kafka

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:7.9.4
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    env_file:
      - ./kafka/.env
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8081:8081"
    profiles:
      - kafka

  kafka-connect:
    build: ./kafka/.
    hostname: kafka-connect
    container_name: kafka-connect
    env_file:
      - ./kafka/.env
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka-schema-registry
    ports:
      - "8083:8083"
    profiles:
      - kafka

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.9.4
    hostname: ksqldb-server
    container_name: ksqldb-server
    env_file:
      - ./kafka/.env
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka-schema-registry
    ports:
      - "8088:8088"
    profiles:
      - kafka

  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    hostname: akhq
    env_file:
      - ./kafka/.env
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-cluster:
              properties:
                bootstrap.servers: "kafka1:19092,kafka2:19093,kafka3:19094"
              schema-registry:
                url: "http://kafka-schema-registry:8081"
              connect:
                - name: "connect-cluster"
                  url: "http://kafka-connect:8083"
              ksql:
                - name: "ksqldb"
                  url: "http://ksqldb-server:8088"
          security:
            default-group: admin
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka-schema-registry
      - kafka-connect
    ports:
      - "9010:8080"
    profiles:
      - kafka